export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const GET_VIDEO_LIST = 'GET_VIDEO_LIST';
export const IS_LOADING_VIDEOS = 'IS_LOADING_VIDEOS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_GOOGLE_ACCESS_TOKEN = 'SET_GOOGLE_ACCESS_TOKEN'

